from tkinter import *
root=Tk()
root.title("Quản lý sinh viên")
root.minsize(height = 500,width=500)
Label(root,text = "ỨNG DỤNG QUẢN LÝ SINH VIÊN",fg='red',font=('cambria',16),width=25).grid(row=0)
listbox = Listbox(root, width=88,height=20).grid(row=1,columnspan=2)
Label(root,text = "Ma SV").grid(row=2,column=0)
Entry(root,width=30).grid(row=2,column=1)
Label(root,text = "Ten SV").grid(row=3,column=0)
Entry(root,width=30).grid(row=3,column=1)
Label(root,text = "Nam sinh cua SV").grid(row=4,column=0)
Entry(root,width=30).grid(row=4,column=1)
button = Frame(root)
Button(button,text='Them').pack(side=LEFT)
Button(button,text='Xem').pack(side=LEFT)
Button(button,text='Sap xep').pack(side=LEFT)
Button(button,text='Thoat',command=root.quit).pack(side=LEFT)
button.grid(row=5,column=1)
root.mainloop() 