from tkinter import *
root = Tk()
stringA=StringVar()
stringB=StringVar()
stringkq=StringVar()
root.title("cac phep toan")
root.minsize(height = 150, width=200)
Label(root,text = "Cong tru nhan chia",fg= "Blue",font=("tahoma",16)).grid(row=0,columnspan=3)
frameButton = Frame(root)
Label(root,text="số a:").grid(row=1,column=1)
Entry(root,width=15,textvariable=stringA).grid(row=1,column=2)
Label(root,text="số b:").grid(row=2,column=1)
Entry(root,width=15,textvariable=stringB).grid(row=2,column=2)
Label(root,text="Kết quả:").grid(row=3,column=1)
Entry(root,width=15,textvariable=stringkq).grid(row=3,column=2)
Button(root,text=  " Thoat",command=root.quit).grid(row=4,column=2)

def CongAction():
    a=float(stringA.get())
    b=float(stringB.get())
    stringkq.set(a+b)
def TruAction():
    a=float(stringA.get())
    b=float(stringB.get())
    stringkq.set(a-b)
def NhanAction():
    a=float(stringA.get())
    b=float(stringB.get())
    stringkq.set(a*b)
def ChiaAction():
    a=float(stringA.get())
    b=float(stringB.get())
    stringkq.set(a/b)
Button(frameButton,text="Cong",command=CongAction).pack(side=TOP,fill=X)
Button(frameButton,text="Tru",command=TruAction).pack(side=TOP,fill=X)
Button(frameButton,text="Nhan",command=NhanAction).pack(side=TOP,fill=X)
Button(frameButton,text="Chia",command=ChiaAction).pack(side=TOP,fill=X)
frameButton.grid(row=1,column=0,rowspan=4)
root.mainloop()
